fullnameOverride: prd-ged-creasol-ocr
image:
  repositoryImage: gitlab.eukles.com:7344/eukles/projects/apache-tika-server
  tag: latest
imagePullSecrets:
  - name: regcred
strategy:
  enabled: true
  type: Recreate
replicaCount: 3
containerPorts:
  http: 9998
resources:
  requests:
    memory: "500M"
    cpu: "1"
  limits:
    memory: "1G"
    cpu: "2"
autoscaling:
  enabled: false
service:
  enabled: true
  port: 9998
  clusterIP: None