apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ged-app-test
  namespace: argocd
spec:
  project: default
  source:
    chart: ged-app
    repoURL: https://github.com/boriscazacu/helm-chart.git
    targetRevision: 1.0.2
    helm:
      valueFiles:
        - applications/mysql/values.yaml
        - applications/app-adminer/values.yaml
        - applications/ged-app/redis/values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: recette