fullnameOverride: prd-ged-grp-cos-mysql
image:
  repositoryImage: gitlab.eukles.com:7344/eukles/ged/app/dev/mariadb
  tag: 10.4
imagePullSecrets:
  - name: regcred
replicaCount: 1
extraEnvVarsSecret: env-all
containerPorts:
  http: 3306
persistence:
  enabled: true
  claimName: pvc-mysql
  accessModes:
    - ReadWriteOnce
  mountPath: /var/lib/mysql
  resources:
    requests:
      storage: 10Gi
  backup:
    enabled: true
    claimName: pvc-backup
    mountPath: /backup/
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
  configMap:
    name: mysqld
    mountPath: /etc/mysql/conf.d/
resources:
  requests:
    memory: "2G"
    cpu: "1"
  limits:
    memory: "8G"
    cpu: "2"
autoscaling:
  enabled: false
service:
  enabled: true
  clusterIP: None
  port: 3306
