fullnameOverride: preprod-eukles
image:
  repositoryImage: gitlab.eukles.com:7344/eukles/ged/app/web
  tag: 23.10.6
initContainers:
  - image: gitlab.eukles.com:7344/eukles/ged/app/migration
    tag: 23.10.6
    name: migration
    extraEnvVarsSecret: env-all
    persistenceEnabled: true
  - image: gitlab.eukles.com:7344/eukles/ged/app/web
    name: migration-es
    tag: 23.10.6
    extraEnvVarsSecret: env-all
    env:
      - name: APPLICATION_USER
        value: application
      - name: CLI_SCRIPT
        value: bash -c
    command:
      - bash
      - -c
      - |
        vendor/bin/propel config:convert && bin/console es:init --no-interaction || bin/console es:sync --no-interaction
imagePullSecrets:
  - name: regcred
strategy:
  enabled: true
  type: Recreate
replicaCount: 1
persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  mountPath: /storage
  resources:
    requests:
      storage: 5Gi
containerPorts:
  http: 80
extraEnvVarsSecret: env-all
resources:
  requests:
    memory: "2G"
    cpu: "1"
  limits:
    memory: "4G"
    cpu: "2"
autoscaling:
  enabled: false

service:
  enabled: true
  port: 80

