{{- if and (.Values.persistence.enabled) (not .Values.persistence.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  {{- if .Values.persistence.annotations }}
  annotations:
    {{- toYaml .Values.persistence.annotations | nindent 4 }}
  {{- end }}
  name: {{ include "ged-app.pvcName" . }}
  labels:
    {{- include "ged-app.labels" . | nindent 4 }}
spec:
  accessModes:
  {{- range .Values.persistence.accessModes }}
    - {{ . | quote }}
  {{- end }}
  {{- with .Values.persistence.resources }}
  resources:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.persistence.storageClassName }}
  storageClassName: {{ .Values.persistence.storageClassName | quote }}
  {{- end }}
---
{{- if and (.Values.persistence.backup.enabled) (not .Values.persistence.backup.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  {{- if .Values.persistence.backup.annotations }}
  annotations:
    {{- toYaml .Values.persistence.backup.annotations | nindent 4 }}
  {{- end }}
  name: {{ include "ged-app.pvcBackupName" . }}
  labels:
    {{- include "ged-app.labels" . | nindent 4 }}
spec:
  accessModes:
  {{- range .Values.persistence.backup.accessModes }}
  - {{ . | quote }}
  {{- end }}
  {{- with .Values.persistence.backup.resources }}
  resources:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.persistence.backup.storageClassName }}
  storageClassName: {{ .Values.persistence.backup.storageClassName | quote }}
  {{- end }}
{{- end }}
{{- end }}
