{{- if .Values.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "ged-app.fullname" . }}
  labels:
    {{- include "ged-app.labels" . | nindent 4 }}
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      {{- include "ged-app.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: {{ .Values.metrics.prometheusPath }}
  targetLabels:
    - app.kubernetes.io/name
  {{- end }}

