fullnameOverride: app-html2pdf
image:
  repositoryImage: gitlab.eukles.com:7344/eukles/ged/services/wkhtmltopdf
  tag: latest
imagePullSecrets:
  - name: regcred
strategy:
  enabled: true
  type: Recreate
replicaCount: 1
containerPorts:
  http: 80
resources:
  requests:
    memory: "100M"
    cpu: "100m"
  limits:
    memory: "500M"
    cpu: "200m"
autoscaling:
  enabled: false
service:
  enabled: true
  port: 8080
  clusterIP: None

