fullnameOverride: prd-ged-creasol-thumbs
image:
  repositoryImage: gitlab.eukles.com:7344/eukles/ged/services/thumbs
  tag: latest
imagePullSecrets:
  - name: regcred
strategy:
  enabled: true
  type: Recreate
replicaCount: 1
containerPorts:
  http: 8000
resources:
  requests:
    memory: "500M"
    cpu: "100m"
  limits:
    memory: "1G"
    cpu: "500m"
autoscaling:
  enabled: false
service:
  enabled: true
  port: 8000
  clusterIP: None
