fullnameOverride: prd-ged-bochq-lad
image:
  repositoryImage: gitlab.eukles.com:7344/eukles/ged/services/ocr-lad
  tag: 1.1-beta4
imagePullSecrets:
  - name: regcred
strategy:
  enabled: true
  type: Recreate
replicaCount: 1
containerPorts:
  http: 5000
resources:
  requests:
    memory: "100M"
    cpu: "10m"
  limits:
    memory: "500M"
    cpu: "200m"
autoscaling:
  enabled: false
service:
  enabled: true
  port: 5000
  clusterIP: None